name: Zig Production Readiness

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prod-ready:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Check formatting
        run: zig fmt --check .

      - name: Build (Debug)
        run: zig build

      - name: Build (ReleaseSafe)
        run: zig build -Doptimize=ReleaseSafe

      - name: Build (ReleaseFast)
        run: zig build -Doptimize=ReleaseFast

      - name: Build (ReleaseSmall)
        run: zig build -Doptimize=ReleaseSmall

      - name: Run tests (Debug)
        run: zig build test

      - name: Run tests (ReleaseSafe)
        run: zig build test -Doptimize=ReleaseSafe

      - name: Run tests (ReleaseFast)
        run: zig build test -Doptimize=ReleaseFast

      - name: Run tests (ReleaseSmall)
        run: zig build test -Doptimize=ReleaseSmall

      - name: Generate documentation
        run: zig build docs || echo "Docs step not defined, skipping."

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: zig-docs
          path: zig-out/docs/

      - name: Upload WASM demo (if present)
        uses: actions/upload-artifact@v3
        with:
          name: wasm-demo
          path: |
            web/index.html
            web/mfs-cube-demo.js
            web/mfs-cube-demo.wasm
        continue-on-error: true

      - name: Upload recent changelog
        uses: actions/upload-artifact@v3
        with:
          name: recent-changes
          path: docs/generated/recent-changes.md
        continue-on-error: true